services:
  backend:
    container_name: queuelens-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    environment:
      - NODE_ENV=production
      - PORT=8060
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: queuelens-redis
    ports:
      - "6379:6379"
    restart: always